# Server
server:
  port: 9460
  servlet:
    context-path: /mobile-service
    
#DB 
spring:
  data:
    mongodb:
      #authentication-database: test
      username: myuser
      password: secret
      database: test
      port: 27017
      host: 13.233.84.237